//------------------
// <auto-generated/>
//------------------

// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

#if !NETCOREAPP
#nullable enable
namespace System.Diagnostics.CodeAnalysis;

/// <summary>
///     Specifies that the method will not return if the associated <see cref="Boolean"/>
///     parameter is passed the specified value.
/// </summary>
[AttributeUsage(AttributeTargets.Parameter, Inherited = false)]
[DebuggerNonUserCode]
[ExcludeFromCodeCoverage]
public sealed class DoesNotReturnIfAttribute : Attribute {
    /// <summary>
    ///     Gets the condition parameter value.
    ///     Code after the method is considered unreachable by diagnostics if the argument
    ///     to the associated parameter matches this value.
    /// </summary>
    public bool ParameterValue { get; }

    /// <summary>
    ///     Initializes a new instance of the <see cref="DoesNotReturnIfAttribute"/>
    ///     class with the specified parameter value.
    /// </summary>
    /// <param name="parameterValue">
    ///     The condition parameter value.
    ///     Code after the method is considered unreachable by diagnostics if the argument
    ///     to the associated parameter matches this value.
    /// </param>
    public DoesNotReturnIfAttribute(bool parameterValue) {
        this.ParameterValue = parameterValue;
    }
}
#endif
